export const CHANGE_LEFT_MENU = 'CHANGE_LEFT_MENU'
export const TOGGLE_NAV_COLLAPSE = 'TOGGLE_NAV_COLLAPSE'
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_PERMISSION = 'GET_USER_PERMISSION'
